// @ts-nocheck
// Generated by tauri-specta from src-tauri. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Overlay finished drawing its frame. */
	overlayReady: (captureId: number, report: OverlayReport) => __TAURI_INVOKE<void>("overlay_ready", { captureId, report }),
	/**  Overlay has painted at least one frame since being shown. */
	overlayVisible: (captureId: number, monitorIndex: number) => __TAURI_INVOKE<void>("overlay_visible", { captureId, monitorIndex }),
	/**  Esc / right-click on an overlay. */
	cancelCapture: (captureId: number) => __TAURI_INVOKE<void>("cancel_capture", { captureId }),
};

/** Events */
export const events = {
	overlayLoad: makeEvent<OverlayLoad>("overlay-load"),
	overlayShown: makeEvent<OverlayShown>("overlay-shown"),
};

/* Types */
export type MonitorInfo = {
	index: number,
	/**  GDI device name, e.g. `\\.\DISPLAY1`. */
	name: string,
	/**  Full monitor bounds including the taskbar, virtual-desktop physical pixels. */
	physicalBounds: PhysicalRect,
	workArea: PhysicalRect,
	/**  Effective DPI / 96. */
	scaleFactor: number | null,
	isPrimary: boolean,
};

/**  Rust → overlay-n: fetch and draw this frame, then call `overlay_ready`. */
export type OverlayLoad = {
	captureId: number,
	monitorIndex: number,
	width: number,
	height: number,
	scaleFactor: number | null,
	format: TransferFormat,
	url: string,
};

/**  Overlay → Rust: frame drawn, with the overlay-side timing. */
export type OverlayReport = {
	monitorIndex: number,
	fetchMs: number | null,
	decodeMs: number | null,
	drawMs: number | null,
	bytes: number,
};

/**  Rust → overlays: you're now shown; reply with `overlay_visible` once painted. */
export type OverlayShown = {
	captureId: number,
};

export type PhysicalPoint = {
	x: number,
	y: number,
};

export type PhysicalRect = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  How frame pixels are encoded for the overlay (benchmarked in docs/perf.md). */
export type TransferFormat = 
/**  Raw RGBA bytes → `putImageData`. */
"rgba" | 
/**  Uncompressed 32bpp BMP → `createImageBitmap`. */
"bmp";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

