// @ts-nocheck
// Generated by tauri-specta from src-tauri. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Overlay page mounted; returns its frame if a capture is waiting on it. */
	overlayPendingLoad: (monitorIndex: number) => __TAURI_INVOKE<{
	captureId: number,
	monitorIndex: number,
	physicalBounds: PhysicalRect,
	width: number,
	height: number,
	scaleFactor: number | null,
	format: TransferFormat,
	url: string,
	dimOpacity: number | null,
	showDimensions: boolean,
	/**  Show the quick-edit toolbar on a region selection (`quickEdit.enabled`). */
	quickEdit: boolean,
	/**  Where quick edit POSTs its annotation and highlight layers. */
	layerUrl: string,
	highlightsUrl: string,
	/**
	 *  The windows on screen at capture time (visible frames, virtual-desktop
	 *  px), topmost first, for window mode (PLAN 3H). `CaptureTarget::Window`
	 *  picks one by its index here.
	 */
	windows: PhysicalRect[],
	/**
	 *  Start in window mode (the window shortcut, PLAN 3H.4), with this
	 *  window under the cursor highlighted.
	 */
	picking: boolean,
	hovered: number | null,
} | null>("overlay_pending_load", { monitorIndex }),
	/**  Overlay finished drawing its frame. */
	overlayReady: (captureId: number, report: OverlayReport) => __TAURI_INVOKE<void>("overlay_ready", { captureId, report }),
	/**  Overlay has painted at least one frame since being shown. */
	overlayVisible: (captureId: number, monitorIndex: number) => __TAURI_INVOKE<void>("overlay_visible", { captureId, monitorIndex }),
	/**  The user started selecting on this monitor; other overlays clear theirs. */
	selectionStarted: (captureId: number, monitorIndex: number) => __TAURI_INVOKE<void>("selection_started", { captureId, monitorIndex }),
	/**
	 *  Window mode (PLAN 3H) turned on or off, or the window under the pointer
	 *  changed, on one overlay; every overlay follows.
	 */
	windowPickChanged: (captureId: number, picking: boolean, hovered: number | null) => __TAURI_INVOKE<void>("window_pick_changed", { captureId, picking, hovered }),
	/**  Confirm: crop and run the after-capture actions. */
	commitSelection: (captureId: number, target: CaptureTarget) => __TAURI_INVOKE<void>("commit_selection", { captureId, target }),
	/**  Esc / right-click on an overlay. */
	cancelCapture: (captureId: number) => __TAURI_INVOKE<void>("cancel_capture", { captureId }),
	/**  Quick edit's Copy / Save on the selection; may close quick edit. */
	quickOutput: (captureId: number, rect: PhysicalRect, action: QuickAction, markup: QuickMarkup) => typedError<QuickOutcome, string>(__TAURI_INVOKE("quick_output", { captureId, rect, action, markup })),
	/**  Quick edit's Done (Enter): deliver the selection with its markup. */
	quickDone: (captureId: number, rect: PhysicalRect, markup: QuickMarkup) => typedError<null, string>(__TAURI_INVOKE("quick_done", { captureId, rect, markup })),
	/**
	 *  Quick edit's "Open in editor": hand the selection and its annotations (a
	 *  JSON array in virtual-desktop px) to a new editor window.
	 */
	quickOpenEditor: (captureId: number, rect: PhysicalRect, annotations: string) => typedError<null, string>(__TAURI_INVOKE("quick_open_editor", { captureId, rect, annotations })),
	/**  Ctrl+O / "Open", step 1: pick image files (none if dismissed). */
	editorPickImages: () => __TAURI_INVOKE<string[]>("editor_pick_images"),
	/**
	 *  Ctrl+O / "Open", step 2, once the page has dealt with its document: the
	 *  first file loads into this editor, the rest in new windows (PLAN 3H.6).
	 */
	editorOpenHere: (paths: string[]) => __TAURI_INVOKE<void>("editor_open_here", { paths }),
	/**  Ctrl+V in an empty editor (PLAN 3G): the clipboard's image loads into it. */
	editorPaste: () => __TAURI_INVOKE<void>("editor_paste"),
	/**  The clipboard's text, for the editor's hidden markup paste (`markupJson.ts`). */
	clipboardText: () => typedError<string, string>(__TAURI_INVOKE("clipboard_text")),
	/**  The Windows accent color, for the accent setting's "Windows" choice. */
	windowsAccent: () => __TAURI_INVOKE<{
	light: string,
	dark: string,
} | null>("windows_accent"),
	/**
	 *  Settings is recording a new shortcut: pause ours, so pressing one is
	 *  recorded instead of starting a capture.
	 */
	hotkeysPause: () => __TAURI_INVOKE<void>("hotkeys_pause"),
	/**  Recording finished: our shortcuts again, as settings have them now. */
	hotkeysResume: () => __TAURI_INVOKE<void>("hotkeys_resume"),
	/**  Whether a just-recorded shortcut can be ours; the reason if not. */
	hotkeyCheck: (hotkey: string) => __TAURI_INVOKE<string | null>("hotkey_check", { hotkey }),
	/**
	 *  A just-recorded markup shortcut (PLAN 3F): spelled as settings store it,
	 *  or why it can't be one (fixed in Vandal, or held by Windows or another app,
	 *  which would take the keys first). Another tool using it is for the caller.
	 */
	shortcutCheck: (shortcut: string) => typedError<string, string>(__TAURI_INVOKE("shortcut_check", { shortcut })),
	/**  Whether Windows keeps PrintScreen for its own screen capture. */
	printScreenOpensSnipping: () => __TAURI_INVOKE<boolean>("print_screen_opens_snipping"),
	/**  Windows Settings › Accessibility › Keyboard (the Print Screen switch). */
	openKeyboardSettings: () => __TAURI_INVOKE<void>("open_keyboard_settings"),
	/**
	 *  Vandal's project page, in the default browser (Settings › About). A fixed
	 *  address: the page can't open others.
	 */
	openProjectPage: () => __TAURI_INVOKE<void>("open_project_page"),
	/**
	 *  Vandal's website, in the default browser (Settings › About). A fixed
	 *  address, like `open_project_page`.
	 */
	openWebsite: () => __TAURI_INVOKE<void>("open_website"),
	/**  The default settings, for "Reset" buttons. */
	defaultSettings: () => __TAURI_INVOKE<Settings>("default_settings"),
	/**  Quick edit: this overlay's selection now has markup (or no longer has). */
	quickMarkupChanged: (captureId: number, monitorIndex: number, has: boolean) => __TAURI_INVOKE<void>("quick_markup_changed", { captureId, monitorIndex, has }),
	/**  Quick edit: bring the overlay with the markup back to the front. */
	quickFocusOverlay: (monitorIndex: number) => __TAURI_INVOKE<void>("quick_focus_overlay", { monitorIndex }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  Validate, save and apply. Returns the settings as stored (values may be
	 *  normalized), or a message to show the user.
	 */
	updateSettings: (settings: Settings) => typedError<Settings, string>(__TAURI_INVOKE("update_settings", { settings })),
	/**  Open (or focus) the settings window, e.g. from the editor's status bar. */
	openSettings: () => __TAURI_INVOKE<void>("open_settings"),
	/**
	 *  Add a color to the presets the given tool uses (the custom color picker's
	 *  "Save as preset"). Returns a message to show if it can't.
	 */
	addColorPreset: (tool: string, color: string) => typedError<null, string>(__TAURI_INVOKE("add_color_preset", { tool, color })),
	/**
	 *  Change (`color` given) or delete (`None`) a preset of the palette the
	 *  given tool uses (right-click on a swatch). Returns a message to show if it can't.
	 */
	editColorPreset: (tool: string, index: number, color: string | null) => typedError<null, string>(__TAURI_INVOKE("edit_color_preset", { tool, index, color })),
	/**
	 *  Folder picker, modal to the calling window. Paths under the user profile
	 *  come back as `%USERPROFILE%\...`.
	 */
	pickFolder: (current: string) => __TAURI_INVOKE<string | null>("pick_folder", { current }),
	/**
	 *  What a file saved now with this template would be called (in the save
	 *  folder, for its auto number).
	 */
	previewFilename: (template: string) => __TAURI_INVOKE<string>("preview_filename", { template }),
	/**
	 *  Open a (settings-style, may contain `%VARS%`) folder in Explorer,
	 *  creating it first so the button always does something.
	 */
	openFolder: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_folder", { path })),
	/**  Editor page mounted: what it shows. `None` if the editor is already gone. */
	editorInit: () => __TAURI_INVOKE<{
	editorId: number,
	/**  Base image size in pixels. */
	width: number,
	height: number,
	/**  The visible part of the base image. */
	crop: PhysicalRect,
	/**  Raw RGBA bytes of the base image. */
	url: string,
	/**  Where to POST the annotation layer before an export. */
	layerUrl: string,
	/**  Where to POST the highlight layer before an export. */
	highlightsUrl: string,
	/**  Annotations from quick edit, if it handed the capture over. */
	markup: HandoffMarkup | null,
	/**
	 *  The name of the image file being edited; None for captures. Files
	 *  ask before closing with unsaved changes instead of running the
	 *  capture on-close actions.
	 */
	file: string | null,
	/**
	 *  Reopened from a notification (PLAN 3D.1): the document as loaded was
	 *  already delivered, so it counts as copied and saved.
	 */
	delivered: boolean,
	/**  No image yet (PLAN 3G): the page shows how to get one. */
	empty: boolean,
} | null>("editor_init"),
	/**  Editor page painted its image; show the window. */
	editorReady: () => __TAURI_INVOKE<void>("editor_ready"),
	/**
	 *  Copy or save `crop` of the base image with `markup` (see [`ExportMarkup`]).
	 *  `layerMs` (render + upload time in the page) is only for the perf log.
	 */
	editorExport: (crop: PhysicalRect, markup: ExportMarkup, action: ExportAction, layerMs: number | null) => typedError<ExportOutcome, string>(__TAURI_INVOKE("editor_export", { crop, markup, action, layerMs })),
	/**
	 *  Ask whether to save unsaved changes before the editor's document goes
	 *  (it closes, or another image replaces it).
	 */
	editorConfirmClose: (reason: LeaveReason) => __TAURI_INVOKE<CloseChoice>("editor_confirm_close", { reason }),
	/**  Start a new region capture from the editor. */
	editorNewCapture: () => __TAURI_INVOKE<void>("editor_new_capture"),
	/**  Show a file selected in Explorer. */
	revealFile: (path: string) => __TAURI_INVOKE<void>("reveal_file", { path }),
	/**
	 *  Installed font families for the text tool's font picker (cached after the
	 *  first call).
	 */
	listFonts: () => __TAURI_INVOKE<string[]>("list_fonts"),
	/**
	 *  The tool styles remembered from earlier windows (JSON text), or null: none
	 *  yet, or `editor.rememberToolStyles` is off.
	 */
	getToolStyles: () => __TAURI_INVOKE<string | null>("get_tool_styles"),
	/**  Remember the tools' current styles (JSON text) for the next window. */
	setToolStyles: (styles: string) => __TAURI_INVOKE<void>("set_tool_styles", { styles }),
	/**
	 *  The text in the editor's image, for redacting it (PLAN 3J): lines of
	 *  words, in image pixels.
	 */
	editorRecognizeText: () => typedError<OcrLine[], OcrError>(__TAURI_INVOKE("editor_recognize_text")),
	/**
	 *  The text in `rect` of a capture (quick edit's selection, PLAN 3J), in
	 *  virtual-desktop physical pixels like `rect`.
	 */
	quickRecognizeText: (captureId: number, rect: PhysicalRect) => typedError<OcrLine[], OcrError>(__TAURI_INVOKE("quick_recognize_text", { captureId, rect })),
};

/** Events */
export const events = {
	overlayClearSelection: makeEvent<OverlayClearSelection>("overlay-clear-selection"),
	overlayLoad: makeEvent<OverlayLoad>("overlay-load"),
	overlayMarkupOwner: makeEvent<OverlayMarkupOwner>("overlay-markup-owner"),
	overlayShown: makeEvent<OverlayShown>("overlay-shown"),
	overlayWindowPick: makeEvent<OverlayWindowPick>("overlay-window-pick"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	windowsAccentChanged: makeEvent<WindowsAccentChanged>("windows-accent-changed"),
};

/* Types */
export type AfterCapture = {
	copyToClipboard?: boolean,
	/**
	 *  Open captures in the editor. The other actions then wait for the
	 *  editor, which copies/saves itself.
	 */
	openEditor?: boolean,
	autoSave?: boolean,
	/**
	 *  Notify when a capture is copied / saved (PLAN 3H.12). A capture that
	 *  was neither always notifies: its notification is the way to save or
	 *  edit it.
	 */
	notifyCopied?: boolean,
	notifySaved?: boolean,
};

export type Appearance = {
	theme?: ThemeMode,
	/**  `"windows"` (the Windows accent color) or a `#rrggbb` the user picked. */
	accent?: string,
};

/**  What the user chose on the overlay. */
export type CaptureTarget = 
/**  Virtual-desktop physical pixels. */
{ kind: "region"; rect: PhysicalRect } | { kind: "monitorUnderCursor" } | { kind: "allMonitors" } | 
/**  An index into `OverlayLoad::windows`. */
{ kind: "window"; index: number };

/**  The answer to "save before closing?". */
export type CloseChoice = "save" | "discard" | "cancel";

/**  How the options bar shows the colors (PLAN 3D.16). */
export type ColorControl = 
/**  The palette as a row of swatches (with the two-color chip). */
"swatches" | 
/**  A button per color that opens the palette. */
"dropdown";

/**  Editor page → Rust on mount: what to show. */
export type EditorInit = {
	editorId: number,
	/**  Base image size in pixels. */
	width: number,
	height: number,
	/**  The visible part of the base image. */
	crop: PhysicalRect,
	/**  Raw RGBA bytes of the base image. */
	url: string,
	/**  Where to POST the annotation layer before an export. */
	layerUrl: string,
	/**  Where to POST the highlight layer before an export. */
	highlightsUrl: string,
	/**  Annotations from quick edit, if it handed the capture over. */
	markup: HandoffMarkup | null,
	/**
	 *  The name of the image file being edited; None for captures. Files
	 *  ask before closing with unsaved changes instead of running the
	 *  capture on-close actions.
	 */
	file: string | null,
	/**
	 *  Reopened from a notification (PLAN 3D.1): the document as loaded was
	 *  already delivered, so it counts as copied and saved.
	 */
	delivered: boolean,
	/**  No image yet (PLAN 3G): the page shows how to get one. */
	empty: boolean,
};

export type EditorOnClose = {
	copy?: boolean,
	save?: boolean,
};

export type EditorSettings = {
	/**  Shape defined in Phase 3. */
	toolPresets?: unknown[],
	defaultTool?: string,
	/**
	 *  Show an "Edit" button on capture notifications. Clicking the
	 *  notification itself opens the editor either way.
	 */
	notificationEditButton?: boolean,
	/**
	 *  What closing the editor does with the image (unless already done since
	 *  the last change).
	 */
	onClose?: EditorOnClose,
	/**
	 *  Tools on the global palette share one current color; off = each tool
	 *  remembers its own.
	 */
	shareColor?: boolean,
	/**  Slot-number badges and shortcut tooltips on the style pickers. */
	showShortcutHints?: boolean,
	/**
	 *  Number buttons in the options bar show their unit ("50%", "10px").
	 *  Off by default: it adds clutter (Richard's call).
	 */
	showButtonUnits?: boolean,
	/**
	 *  With a drawing tool, pressing on an object selects it (off: drawing
	 *  tools always draw). Ctrl flips this for one press.
	 */
	drawingToolsSelect?: boolean,
	/**
	 *  New windows start with the tools' styles as last used (colors, widths,
	 *  fonts...), also after a restart. Off: they start from the defaults.
	 */
	rememberToolStyles?: boolean,
	/**  Warn before the first save over an opened image file (PLAN 2D). */
	confirmOverwrite?: boolean,
};

/**  What to do with the finished image. */
export type ExportAction = "copy" | 
/**  Save with the file-name template into the save folder. */
"save" | 
/**  Ask where to save. */
"saveAs";

/**  What goes onto the cropped base in an export, bottom to top. */
export type ExportMarkup = {
	/**  Pixelated or blurred areas, in base-image px (PLAN 3D.3). */
	redactions: Redaction[],
	/**  Multiply in the highlight layer POSTed to `highlightsUrl` just before. */
	withHighlights: boolean,
	/**  Composite the annotation layer POSTed to `layerUrl` just before. */
	withLayer: boolean,
};

export type ExportOutcome = { kind: "copied" } | { kind: "saved"; path: string } | 
/**  Save As was dismissed. */
{ kind: "cancelled" };

/**  How the font picker shows its fonts. */
export type FontControl = "dropdown" | 
/**  A stepped slider with the name under it (custom lists of up to 10). */
"stepped";

/**
 *  A font picker (the text tool's, and the step markers'). The user's list is kept while `source` is
 *  `System`, so switching back brings it back (Richard's call, 2C.3). Files
 *  from before 2C.3 (`{"source":"system",...}` without `fonts`) load as is.
 */
export type FontPicker = {
	source?: FontSource,
	fonts?: string[],
	/**
	 *  Kept as chosen: the page shows a dropdown whenever a stepped slider
	 *  doesn't fit (the system list, or more than 10 fonts).
	 */
	control?: FontControl,
};

/**  Where the font picker's fonts come from. */
export type FontSource = 
/**  Every installed font. */
"system" | 
/**  The user's own list, in their order. */
"custom" | 
/**
 *  The text tool's fonts and control ("Same as Text tool"). Only the step
 *  font offers it (PLAN 3D.13); the text tool's own picker can't.
 */
"text";

/**
 *  Quick edit's annotations, handed to the editor still editable (PLAN 2B.3).
 *  The page's own JSON: Rust only carries it and says how to shift it.
 */
export type HandoffMarkup = {
	/**  A JSON array of annotations, in virtual-desktop physical px. */
	annotations: string,
	/**  Add to the annotations' coordinates to get base-image pixels. */
	dx: number,
	dy: number,
};

export type History = {
	keepFramesInMemory?: number,
};

/**  Human-readable accelerators, e.g. `"Win+Shift+F12"`. `None` = unassigned. */
export type Hotkeys = {
	region?: string | null,
	fullscreen?: string | null,
	/**  Window capture (PLAN 3H.4): the overlay opens in window mode. */
	window?: string | null,
	repeatLast?: string | null,
};

/**  What clicking the tray icon or launching Vandal does (PLAN 3G). */
export type IconAction = 
/**  A region capture. */
"capture" | 
/**  An empty editor window. */
"editor";

/**  Why an editor's document is about to go, for the "save first?" question. */
export type LeaveReason = "close" | 
/**  Another image opens in its place (PLAN 3H.6). */
"open" | 
/**  A capture started from it will take its place (PLAN 3H.7). */
"capture";

export type MonitorInfo = {
	index: number,
	/**  GDI device name, e.g. `\\.\DISPLAY1`. */
	name: string,
	/**  Full monitor bounds including the taskbar, virtual-desktop physical pixels. */
	physicalBounds: PhysicalRect,
	workArea: PhysicalRect,
	/**  Effective DPI / 96. */
	scaleFactor: number | null,
	isPrimary: boolean,
};

/**
 *  A number control: a free range, or a list of presets shown as a stepped
 *  slider, a dropdown or buttons. Lists are kept ascending.
 */
export type NumberPicker = { control: "slider"; min: number | null; max: number | null } | { control: "stepped"; values: (number | null)[] } | { control: "dropdown"; values: (number | null)[] } | { control: "buttons"; values: (number | null)[] };

export type OcrError = 
/**  Windows has no OCR language installed that it can use. */
{ kind: "noLanguage" } | { kind: "failed"; message: string };

/**
 *  Words in reading order. Lines come in the engine's order, which keeps
 *  columns together.
 */
export type OcrLine = {
	words: OcrWord[],
};

/**
 *  One recognized word, its box in the image's pixels (rounded outward, so
 *  it covers all of the word's ink).
 */
export type OcrWord = {
	text: string,
	rect: PhysicalRect,
};

/**  Rust → overlays: a selection started on `monitor_index`; clear yours. */
export type OverlayClearSelection = {
	captureId: number,
	monitorIndex: number,
};

/**  Rust → overlay-n: fetch and draw this frame, then call `overlay_ready`. */
export type OverlayLoad = {
	captureId: number,
	monitorIndex: number,
	physicalBounds: PhysicalRect,
	width: number,
	height: number,
	scaleFactor: number | null,
	format: TransferFormat,
	url: string,
	dimOpacity: number | null,
	showDimensions: boolean,
	/**  Show the quick-edit toolbar on a region selection (`quickEdit.enabled`). */
	quickEdit: boolean,
	/**  Where quick edit POSTs its annotation and highlight layers. */
	layerUrl: string,
	highlightsUrl: string,
	/**
	 *  The windows on screen at capture time (visible frames, virtual-desktop
	 *  px), topmost first, for window mode (PLAN 3H). `CaptureTarget::Window`
	 *  picks one by its index here.
	 */
	windows: PhysicalRect[],
	/**
	 *  Start in window mode (the window shortcut, PLAN 3H.4), with this
	 *  window under the cursor highlighted.
	 */
	picking: boolean,
	hovered: number | null,
};

/**
 *  Rust → overlays: the overlay on `owner` has quick-edit markup (None: none
 *  has). The others stop starting selections, so it can't be thrown away.
 */
export type OverlayMarkupOwner = {
	captureId: number,
	owner: number | null,
};

/**  Overlay → Rust: frame drawn, with the overlay-side timing. */
export type OverlayReport = {
	monitorIndex: number,
	fetchMs: number | null,
	decodeMs: number | null,
	drawMs: number | null,
	bytes: number,
};

export type OverlaySettings = {
	dimOpacity?: number | null,
	showLoupe?: boolean,
	showDimensions?: boolean,
};

/**  Rust → overlays: you're now shown; reply with `overlay_visible` once painted. */
export type OverlayShown = {
	captureId: number,
};

/**
 *  Rust → overlays: window mode is on or off, and which window (an index into
 *  `OverlayLoad::windows`) is under the pointer, so a window spanning
 *  monitors is highlighted on each of them.
 */
export type OverlayWindowPick = {
	captureId: number,
	picking: boolean,
	hovered: number | null,
};

export type PhysicalPoint = {
	x: number,
	y: number,
};

export type PhysicalRect = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  A quick-edit toolbar action that doesn't have to end the capture. */
export type QuickAction = "copy" | "save";

/**
 *  Quick edit (PLAN Phase 2): a toolbar on the selection screen to copy, save
 *  or mark up a region capture before it's delivered.
 */
export type QuickEditSettings = {
	/**  Off: the selection screen works as in Phase 1 (Enter captures). */
	enabled?: boolean,
	/**  Ctrl+C / Copy also closes quick edit (and runs the actions still pending). */
	closeOnCopy?: boolean,
	/**  Ctrl+S / Save also closes quick edit. */
	closeOnSave?: boolean,
};

/**
 *  Quick edit's markup, as the page describes it with each action: which
 *  layers it just uploaded, its redactions, its revision, and the annotations
 *  themselves (a JSON array in virtual-desktop px) in case the editor takes
 *  over.
 */
export type QuickMarkup = {
	layer: boolean,
	highlights: boolean,
	/**  Pixelated or blurred areas in virtual-desktop px, bottom to top (PLAN 3D.4). */
	redactions: Redaction[],
	revision: number,
	annotations: string,
};

/**  What a quick-edit action did. */
export type QuickOutcome = {
	/**  Quick edit closed (per `quickEdit.closeOnCopy` / `closeOnSave`). */
	closed: boolean,
	/**  A saved file, for the toolbar's message. */
	path: string | null,
};

export type RedactMode = 
/**  Opaque black: nothing of the original survives. */
"solid" | "pixelate" | "blur";

/**  One redaction, in the base image's pixels. */
export type Redaction = {
	rect: PhysicalRect,
	mode: RedactMode,
	/**
	 *  Pixelate: block size. Blur: box radius (three passes). Source px.
	 *  Solid: unused.
	 */
	strength: number,
};

export type SaveSettings = {
	/**  May contain `%ENV%` variables. */
	directory?: string,
	/**
	 *  Tokens: `{yyyy} {MM} {dd} {HH} {mm} {ss}`, and `{n}`, `{nn}`... for
	 *  an auto number (PLAN 3H.8).
	 */
	filenameTemplate?: string,
	format?: string,
	/**  Offer a "Save" button on the capture notification when not auto-saved. */
	notificationSaveButton?: boolean,
};

export type Settings = {
	version?: number,
	hotkeys?: Hotkeys,
	/**  The markup's keys for tools and swapping colors (PLAN 3F). */
	shortcuts?: Shortcuts,
	afterCapture?: AfterCapture,
	save?: SaveSettings,
	overlay?: OverlaySettings,
	quickEdit?: QuickEditSettings,
	editor?: EditorSettings,
	/**  How the app looks (PLAN 3A). */
	appearance?: Appearance,
	/**  Style pickers for the markup tools. */
	styles?: Styles,
	startup?: Startup,
	history?: History,
	tray?: TraySettings,
};

/**  Rust → all windows: settings changed (from any source), here's the new state. */
export type SettingsChanged = Settings;

/**  Human-readable, e.g. `"V"` or `"Ctrl+L"`. `None` = no shortcut. */
export type Shortcuts = {
	select?: string | null,
	pen?: string | null,
	highlighter?: string | null,
	line?: string | null,
	arrow?: string | null,
	rect?: string | null,
	ellipse?: string | null,
	text?: string | null,
	callout?: string | null,
	redact?: string | null,
	spotlight?: string | null,
	step?: string | null,
	/**  The editor's crop. */
	crop?: string | null,
	/**  Swap the two colors (PLAN 3D.15). */
	swapColors?: string | null,
};

export type Startup = {
	launchOnLogin?: boolean,
	/**
	 *  Launching Vandal (its desktop or Start menu icon). While it's running:
	 *  this. When it isn't: it starts in the tray, and opens the editor if
	 *  that's the choice, but never starts a capture. Never on login.
	 */
	launchAction?: IconAction,
};

export type Styles = {
	/**  Color presets in the user's order, `#rrggbb`. */
	palette?: string[],
	/**  How the colors show in the options bar. */
	colorControl?: ColorControl,
	/**  Line width in source px. */
	width?: NumberPicker,
	/**  The text tool's font. */
	font?: FontPicker,
	/**  The text tool's size in pt. */
	fontSize?: NumberPicker,
	/**  Redact's pixelate block size in source px (PLAN 3D.3). */
	pixelate?: NumberPicker,
	/**  Redact's blur radius in source px. */
	blur?: NumberPicker,
	/**  Spotlight's darkness outside, in % (PLAN 3D.7). */
	spotlight?: NumberPicker,
	/**  Step markers' size in source px (PLAN 3D.13). */
	stepSize?: NumberPicker,
	/**
	 *  Rounded corners (rectangles, Spotlight's rectangle) in source px (PLAN
	 *  3D.17): 0 is always a choice, and never buttons.
	 */
	cornerRadius?: NumberPicker,
	/**  Step markers' font; by default the text tool's choices. */
	stepFont?: FontPicker,
	/**  Per-tool overrides, keyed by tool id (`"highlighter"`, ...). */
	tools?: { [key in string]: ToolStyles },
};

/**  Light, dark, or following Windows. */
export type ThemeMode = "system" | "light" | "dark";

/**
 *  A tool's own palette, width picker and/or color control, used instead of
 *  the global ones.
 */
export type ToolStyles = {
	palette?: string[] | null,
	width?: NumberPicker | null,
	colorControl?: ColorControl | null,
};

/**  How frame pixels are encoded for the overlay (benchmarked in docs/perf.md). */
export type TransferFormat = 
/**  Raw RGBA bytes → `putImageData`. */
"rgba" | 
/**  Uncompressed 32bpp BMP → `createImageBitmap`. */
"bmp";

export type TraySettings = {
	/**  Clicking the tray icon (PLAN 3G). */
	clickAction?: IconAction,
};

/**
 *  The Windows accent color as Windows 11 apps use it: a darker shade on
 *  light backgrounds, a lighter one on dark (WinUI's AccentDark1 and
 *  AccentLight2), as `#rrggbb`.
 */
export type WindowsAccent = {
	light: string,
	dark: string,
};

/**  Rust → pages: the Windows accent changed (None: not available). */
export type WindowsAccentChanged = WindowsAccent | null;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

