mod bench;
mod capture;
mod commands;
mod compose;
// Some of these APIs are first used by the editor (Phase 2) and window snap (Phase 4).
#[allow(dead_code)]
mod frames;
#[allow(dead_code)]
mod geometry;
mod hotkeys;
mod monitors;
mod output;
mod overlay;
mod protocol;
mod session;
mod settings;
mod state;
mod tray;

use std::sync::{Mutex, RwLock};

use tauri::{Manager, RunEvent, WindowEvent};
use tauri_specta::{collect_commands, collect_events};

use crate::capture::gdi::GdiCapturer;
use crate::frames::FrameStore;
use crate::protocol::TransferFormat;
use crate::state::AppState;

fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::overlay_pending_load,
            commands::overlay_ready,
            commands::overlay_visible,
            commands::selection_started,
            commands::commit_selection,
            commands::cancel_capture,
        ])
        .events(collect_events![
            session::OverlayLoad,
            session::OverlayShown,
            session::OverlayClearSelection,
        ])
        .typ::<geometry::MonitorInfo>()
        .typ::<geometry::PhysicalPoint>()
        .typ::<settings::Settings>()
}

#[cfg(debug_assertions)]
fn export_bindings() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/shared/bindings.ts");
    specta_builder()
        .export(
            specta_typescript::Typescript::default().header(
                "// @ts-nocheck\n// Generated by tauri-specta from src-tauri. Do not edit.\n",
            ),
            path,
        )
        .expect("failed to export TS bindings");
}

/// Initial overlay transfer format; `CAPTURE_TRANSFER=bmp` to override.
fn transfer_format_from_env() -> TransferFormat {
    match std::env::var("CAPTURE_TRANSFER").as_deref() {
        Ok("bmp") => TransferFormat::Bmp,
        _ => TransferFormat::Rgba,
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    #[cfg(debug_assertions)]
    export_bindings();

    let specta = specta_builder();

    let bench = std::env::var_os("CAPTURE_BENCH").is_some();
    let mut builder = tauri::Builder::default();
    if !bench {
        // Must be the first plugin. A second launch triggers a capture instead.
        builder = builder.plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            session::start_region(app);
        }));
    }
    let app = builder
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_autostart::Builder::new().build())
        .plugin(hotkeys::plugin())
        .register_asynchronous_uri_scheme_protocol(protocol::SCHEME, protocol::handle)
        .invoke_handler(specta.invoke_handler())
        .setup(move |app| {
            specta.mount_events(app);

            if monitors::is_per_monitor_v2() {
                eprintln!("[startup] DPI awareness: Per-Monitor V2");
            } else {
                eprintln!("[startup] WARNING: process is NOT Per-Monitor V2 DPI aware; captures will be misaligned");
            }

            let monitors = monitors::enumerate()?;
            for m in &monitors {
                eprintln!(
                    "[startup] monitor {} {}: {:?} scale {}{}",
                    m.index,
                    m.name,
                    m.physical_bounds,
                    m.scale_factor,
                    if m.is_primary { " (primary)" } else { "" }
                );
            }

            let settings = settings::load(app.handle());
            app.manage(AppState {
                capturer: Box::new(GdiCapturer),
                frames: Mutex::new(FrameStore::new(
                    settings.history.keep_frames_in_memory as usize,
                )),
                monitors: RwLock::new(monitors.clone()),
                settings: RwLock::new(settings.clone()),
                session: Mutex::new(None),
                transfer_format: Mutex::new(transfer_format_from_env()),
                perf_log: Mutex::new(Vec::new()),
            });

            overlay::create_pool(app.handle(), &monitors)?;
            overlay::watch_displays(app.handle());
            if bench {
                bench::maybe_start(app.handle());
                return Ok(());
            }

            hotkeys::register(app.handle(), &settings.hotkeys);
            tray::create(app.handle(), &settings)?;
            // Dev builds leave the Run key alone unless toggled from the tray.
            #[cfg(not(debug_assertions))]
            tray::apply_autostart(app.handle(), settings.startup.launch_on_login);
            eprintln!("[startup] ready");
            Ok(())
        })
        .on_window_event(|window, event| {
            // Alt+F4 on an overlay must cancel, not destroy a pooled window.
            if let WindowEvent::CloseRequested { api, .. } = event {
                if overlay::is_overlay(window.label()) {
                    api.prevent_close();
                    if let Some((id, _)) = session::current(window.app_handle()) {
                        session::cancel(window.app_handle(), id);
                    }
                }
            }
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    app.run(|_app, event| {
        // Tray-resident: no windows visible is the normal state.
        if let RunEvent::ExitRequested {
            code: None, api, ..
        } = event
        {
            api.prevent_exit();
        }
    });
}
