mod appearance;
mod bench;
mod browser_keys;
mod capture;
mod cli;
mod commands;
mod compose;
mod decode;
mod editor;
mod encode;
mod fonts;
// Some of these APIs are first used by the editor (Phase 2) and window snap (not built yet).
#[allow(dead_code)]
mod frames;
#[allow(dead_code)]
mod geometry;
mod hotkeys;
mod monitors;
mod output;
mod overlay;
mod protocol;
mod redact;
mod session;
mod settings;
mod settings_window;
mod shortcuts;
mod state;
mod styles;
mod tool_styles;
mod tray;

use std::sync::{Mutex, RwLock};

use tauri::{Manager, RunEvent, WindowEvent};
use tauri_specta::{collect_commands, collect_events};

use crate::capture::gdi::GdiCapturer;
use crate::frames::FrameStore;
use crate::protocol::TransferFormat;
use crate::state::AppState;

fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::overlay_pending_load,
            commands::overlay_ready,
            commands::overlay_visible,
            commands::selection_started,
            commands::commit_selection,
            commands::cancel_capture,
            commands::quick_output,
            commands::quick_done,
            commands::quick_open_editor,
            commands::editor_open_image,
            commands::editor_paste,
            commands::windows_accent,
            commands::hotkeys_pause,
            commands::hotkeys_resume,
            commands::hotkey_check,
            commands::shortcut_check,
            commands::print_screen_opens_snipping,
            commands::open_keyboard_settings,
            commands::default_settings,
            commands::quick_markup_changed,
            commands::quick_focus_overlay,
            commands::get_settings,
            commands::update_settings,
            commands::open_settings,
            commands::add_color_preset,
            commands::edit_color_preset,
            commands::pick_folder,
            commands::preview_filename,
            commands::open_folder,
            commands::editor_init,
            commands::editor_ready,
            commands::editor_export,
            commands::editor_confirm_close,
            commands::editor_new_capture,
            commands::reveal_file,
            commands::list_fonts,
            commands::get_tool_styles,
            commands::set_tool_styles,
        ])
        .events(collect_events![
            session::OverlayLoad,
            session::OverlayShown,
            session::OverlayClearSelection,
            session::OverlayMarkupOwner,
            appearance::WindowsAccentChanged,
            settings::SettingsChanged,
        ])
        .typ::<geometry::MonitorInfo>()
        .typ::<geometry::PhysicalPoint>()
        .typ::<settings::Settings>()
}

#[cfg(debug_assertions)]
fn export_bindings() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/shared/bindings.ts");
    specta_builder()
        .export(
            specta_typescript::Typescript::default().header(
                "// @ts-nocheck\n// Generated by tauri-specta from src-tauri. Do not edit.\n",
            ),
            path,
        )
        .expect("failed to export TS bindings");
}

/// User-facing app name (`productName`), e.g. "Vandal" or, for dev
/// builds, "Vandal Dev".
pub(crate) fn product_name(app: &tauri::AppHandle) -> String {
    app.config()
        .product_name
        .clone()
        .unwrap_or_else(|| app.package_info().name.clone())
}

/// Initial overlay transfer format; `CAPTURE_TRANSFER=bmp` to override.
fn transfer_format_from_env() -> TransferFormat {
    match std::env::var("CAPTURE_TRANSFER").as_deref() {
        Ok("bmp") => TransferFormat::Bmp,
        _ => TransferFormat::Rgba,
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    #[cfg(debug_assertions)]
    export_bindings();

    let specta = specta_builder();

    let bench = std::env::var_os("CAPTURE_BENCH").is_some();
    let mut builder = tauri::Builder::default();
    if !bench {
        // Must be the first plugin. A second launch triggers a capture instead.
        // `--settings` opens Settings, `--edit <path>` opens an image; a
        // plain second launch starts a capture.
        builder = builder.plugin(tauri_plugin_single_instance::init(|app, args, cwd| {
            let files = cli::edit_paths(&args, std::path::Path::new(&cwd));
            if args.iter().any(|a| a == "--settings") {
                settings_window::open(app);
            } else if files.is_empty() {
                session::start_region(app);
            }
            for file in files {
                editor::open_file(app, &file);
            }
        }));
    }
    let app = builder
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_autostart::Builder::new().build())
        .plugin(hotkeys::plugin())
        .register_asynchronous_uri_scheme_protocol(protocol::SCHEME, protocol::handle)
        .invoke_handler(specta.invoke_handler())
        .setup(move |app| {
            specta.mount_events(app);

            if monitors::is_per_monitor_v2() {
                eprintln!("[startup] DPI awareness: Per-Monitor V2");
            } else {
                eprintln!("[startup] WARNING: process is NOT Per-Monitor V2 DPI aware; captures will be misaligned");
            }

            let monitors = monitors::enumerate()?;
            for m in &monitors {
                eprintln!(
                    "[startup] monitor {} {}: {:?} scale {}{}",
                    m.index,
                    m.name,
                    m.physical_bounds,
                    m.scale_factor,
                    if m.is_primary { " (primary)" } else { "" }
                );
            }

            let settings = settings::load(app.handle());
            app.manage(AppState {
                capturer: Box::new(GdiCapturer),
                frames: Mutex::new(FrameStore::new(
                    settings.history.keep_frames_in_memory as usize,
                )),
                monitors: RwLock::new(monitors.clone()),
                settings: RwLock::new(settings.clone()),
                session: Mutex::new(None),
                transfer_format: Mutex::new(transfer_format_from_env()),
                recent_images: Mutex::new(output::RecentImages::new()),
                editors: Mutex::new(editor::Editors::default()),
                perf_log: Mutex::new(Vec::new()),
            });

            overlay::create_pool(app.handle(), &monitors)?;
            overlay::watch_displays(app.handle());
            appearance::watch_windows_accent(app.handle());
            if bench {
                bench::maybe_start(app.handle());
                return Ok(());
            }

            hotkeys::register(app.handle(), &settings.hotkeys);
            tray::create(app.handle(), &settings)?;
            // Dev builds leave the Run key alone unless toggled from the tray.
            #[cfg(not(debug_assertions))]
            tray::apply_autostart(app.handle(), settings.startup.launch_on_login);
            if std::env::args().any(|a| a == "--settings") {
                settings_window::open(app.handle());
            }
            let args: Vec<String> = std::env::args().collect();
            let cwd = std::env::current_dir().unwrap_or_default();
            for file in cli::edit_paths(&args, &cwd) {
                editor::open_file(app.handle(), &file);
            }
            eprintln!("[startup] ready");
            Ok(())
        })
        .on_window_event(|window, event| match event {
            // Alt+F4 on an overlay must cancel, not destroy a pooled window.
            WindowEvent::CloseRequested { api, .. } if overlay::is_overlay(window.label()) => {
                api.prevent_close();
                if let Some((id, _)) = session::current(window.app_handle()) {
                    session::cancel(window.app_handle(), id);
                }
            }
            WindowEvent::CloseRequested { .. } if editor::id_from_label(window.label()).is_some() => {
                editor::closing(window.app_handle(), window);
            }
            WindowEvent::Destroyed => editor::destroyed(window.app_handle(), window.label()),
            // Files dropped on an editor open in editors of their own; an
            // empty editor takes the first (PLAN 3G).
            WindowEvent::DragDrop(tauri::DragDropEvent::Drop { paths, .. })
                if editor::id_from_label(window.label()).is_some() =>
            {
                let mut into = editor::empty_editor(window.app_handle(), window.label());
                for path in paths {
                    editor::open_file_in(window.app_handle(), path, into.take());
                }
            }
            _ => {}
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    app.run(|_app, event| {
        // Tray-resident: no windows visible is the normal state.
        if let RunEvent::ExitRequested {
            code: None, api, ..
        } = event
        {
            api.prevent_exit();
        }
    });
}
